repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0  # Use the latest version or a specific version
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files

  - repo: https://github.com/pre-commit/autoflake
    rev: v1.4  # Use the latest version or a specific version
    hooks:
      - id: autoflake
        args:
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --ignore-init-module-imports
