"""Add send_alert column to favorite_locations

Revision ID: 90c6535927e9
Revises: 0072c8af6051
Create Date: 2024-10-03 14:06:11.405454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90c6535927e9'
down_revision: Union[str, None] = '0072c8af6051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_locations', sa.Column('send_alert', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('favorite_locations', 'send_alert')
    # ### end Alembic commands ###
