"""Add weather_data table

Revision ID: 9f753ee06805
Revises: bcaeef7f45cc
Create Date: 2024-07-25 14:34:00.525549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f753ee06805'
down_revision: Union[str, None] = 'bcaeef7f45cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite_locations', sa.Column('name', sa.String(), nullable=True))
    op.add_column('favorite_locations', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('favorite_locations', sa.Column('longitude', sa.String(), nullable=True))
    op.add_column('favorite_locations', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.drop_index('ix_favorite_locations_city', table_name='favorite_locations')
    op.drop_index('ix_favorite_locations_country', table_name='favorite_locations')
    op.create_index(op.f('ix_favorite_locations_name'), 'favorite_locations', ['name'], unique=False)
    op.drop_constraint('favorite_locations_user_id_fkey', 'favorite_locations', type_='foreignkey')
    op.create_foreign_key(None, 'favorite_locations', 'users', ['owner_id'], ['id'])
    op.drop_column('favorite_locations', 'city')
    op.drop_column('favorite_locations', 'user_id')
    op.drop_column('favorite_locations', 'country')
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.add_column('weather_data', sa.Column('location_name', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('weather_data', sa.Column('weather_description', sa.String(), nullable=True))
    op.add_column('weather_data', sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('weather_data', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('weather_data', 'humidity',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_index('ix_weather_data_city', table_name='weather_data')
    op.create_foreign_key(None, 'weather_data', 'users', ['user_id'], ['id'])
    op.drop_column('weather_data', 'wind_speed')
    op.drop_column('weather_data', 'city')
    op.drop_column('weather_data', 'pressure')
    op.drop_column('weather_data', 'country')
    op.drop_column('weather_data', 'description')
    op.drop_column('weather_data', 'weather')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_data', sa.Column('weather', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('pressure', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('weather_data', sa.Column('wind_speed', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'weather_data', type_='foreignkey')
    op.create_index('ix_weather_data_city', 'weather_data', ['city'], unique=False)
    op.alter_column('weather_data', 'humidity',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.drop_column('weather_data', 'user_id')
    op.drop_column('weather_data', 'recorded_at')
    op.drop_column('weather_data', 'weather_description')
    op.drop_column('weather_data', 'longitude')
    op.drop_column('weather_data', 'latitude')
    op.drop_column('weather_data', 'location_name')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'username')
    op.add_column('favorite_locations', sa.Column('country', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('favorite_locations', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('favorite_locations', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'favorite_locations', type_='foreignkey')
    op.create_foreign_key('favorite_locations_user_id_fkey', 'favorite_locations', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_favorite_locations_name'), table_name='favorite_locations')
    op.create_index('ix_favorite_locations_country', 'favorite_locations', ['country'], unique=False)
    op.create_index('ix_favorite_locations_city', 'favorite_locations', ['city'], unique=False)
    op.drop_column('favorite_locations', 'owner_id')
    op.drop_column('favorite_locations', 'longitude')
    op.drop_column('favorite_locations', 'latitude')
    op.drop_column('favorite_locations', 'name')
    # ### end Alembic commands ###
